
// Auto-generated by AutoPilot on 29-07-2023 at 02:02:26


const express = require('express');
const router = express.Router();

//Importing the list of sherlock stories
const stories = ["A Scandal in Bohemia", "The Red-Headed League", "A Case of Identity", "The Boscombe Valley Mystery", "The Five Orange Pips"];

//Route to get random story
router.get('/facts', (req, res) => {
    //Generate a random index between 0 and 5
    const randomIndex = Math.floor(Math.random() * 5);
    //Return the story at the generated random index
    res.send(stories[randomIndex]);
});

module.exports = router;